service: cronjob-scheduler

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'qa'}
  environment: ${file(./config/env.${self:provider.stage}.json)}
  iam:
    role:
      statements: ${file(./config/serverless/db.iam.role.yaml)}

resources:
  Resources: ${file(./config/serverless/resources/dynamo.commit-messages.table.yaml)}

custom:
  schedulerRate: rate(1 minute)
  enabled: true
  tableName: ${self:provider.environment.DbTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: schedule-commit-message-${self:provider.stage}
          description: get commit messages each minute
          enabled: ${self:custom.enabled}
